title: <p align="center"> Piyali Podder </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/piyali-podder-610b78175">LinkedIn</a> |
  <a href="https://github.com/PiyaP-lab/">GitHub</a>
  
  <br>   
  I'm working on Automation Testing projects along with DataScience and AI/ML projects as a part of GEN-AI Practice
  I am a passionate innovator and loves to learn and upskill on new Technologies and implement the same
  I have a AI/ML Testing Expertise involving around LLM integration testing,Prompt engineering validation and 
  Vector database testing
  <br>
  </p>



theme: jekyll-theme-minimal
